### ISSUE TITLE
Issues with manual enrolment

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-enrol-grabber#1]
The plugin allows to enrol additional users via it manually. However, when I attempt so, the roles selection is wrong:

![screenshot_2016-10-27_10-16-51](https://cloud.githubusercontent.com/assets/85831/19759779/c781db50-9c2e-11e6-8548-930d5492e445.png)

**Comment by cperves** [comment]
Can't reproduce that trouble in that select but in other one

**Comment by cperves** [comment]
Can't reproduce this
But remove correctly enrollment options that was not well removed from manual enrol example (enrollment period and expiration)

**Comment by cperves** [comment]
Can't reproduce this
But remove correctly enrollment options that was not well removed from manual enrol example (enrollment period and expiration)

**Comment by cperves** [comment]
Can't reproduce this
But remove correctly enrollment options that was not well removed from manual enrol example (enrollment period and expiration)

**Comment by cperves** [comment]
Can't reproduce this
But remove correctly enrollment options that was not well removed from manual enrol example (enrollment period and expiration)

**Comment by cperves** [comment]
fixed
