### ISSUE TITLE
What is the meaning of the Default role

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-enrol-grabber#2]
All fields look natural for the method, but this one "Default role". What is its purpose and behaviour? I understood this plugin would not change the role assigned by the original method. Is it only for manually added enrolments? There is no associated help to it.

**Comment by cperves** [comment]
This is for manually added enrolments such like into enrol manual method
That seems to be usefull since most of users don't take of role choice letting default one.
Tht's the reason why I let Default role setting.
