### ISSUE TITLE
Mention the origin of the files

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-enrol-grabber#6]
Some files are apparent copies of their enrol_manual origins - e.g. ajax.php. Yet their `@author` and `@copyright` tags look like they were your original work. In these cases, what works best is to keep the original copyrights and authors, and append yourself. So the file docblock would read like

```
 * @copyright 2016 Celine Perves <cperves@unistra.fr>, Unistra {@link http://unistra.fr}
 * @copyright  2010 Sam Hemelryk
 * @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
```

Such a form makes it clear that Sam is the original author, but you should be blamed for the file now.

**Comment by cperves** [comment]
Thank you I never know how to mention original author

**Comment by cperves** [comment]
fixed
